### ISSUE TITLE
)

### ISSUE THREAD

**Issue by Vladddd46** [NazarWild/UniPal_bot#1]
TOKEN = '7431853129:AAE09L0mHj_9JR9NEiz53FlUYDcDuysSgdc'

**Comment by NazarWild** [comment]
Thank you.

ср, 25 груд. 2024 р., 14:23 користувач Vladyslav ***@***.***>
пише:

**Comment by NazarWild** [comment]
Дякую, що помітив і повідомив.
Токен уже змінений в телеграмі і це лише студентський проект.
